id: AEE8B5421
title: 'Dispelling the Anguish of Existence and Quiescence: A Prayer of Calling the
  Guru from Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:10:43.726462
  last_modified_at: 2022-03-01 03:10:43.726466
