id: AEE8B5421
title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:10:43.730687
  last_modified_at: 2022-03-01 03:10:43.730690
