id: AEE8B5421
title: Calling the Guru From Afar
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:10:43.713394
  last_modified_at: 2022-03-01 03:10:43.713396
