id: AEE8B5421
title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the Guru from
  Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:10:43.737630
  last_modified_at: 2022-03-01 03:10:43.737633
