id: AEE8B5421
title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:10:43.723763
  last_modified_at: 2022-03-01 03:10:43.723766
