id: AEE8B5421
title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru from
  Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:10:43.735532
  last_modified_at: 2022-03-01 03:10:43.735535
