id: AEE8B5421
title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
  the Great Omniscient Jonangpa from Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:10:43.712087
  last_modified_at: 2022-03-01 03:10:43.712090
