id: AEE8B5421
title: 'Gyang Lu: A Song of Calling from Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:10:43.728951
  last_modified_at: 2022-03-01 03:10:43.728954
